---
functional:
  - Предоставление возможности пользователям соревноваться друг с другом в решении задач.
  - Просмотр кода другого игрока в режиме реального времени.
  - Реализация дополнительных функциональностей, таких как рейтинги, игра с ботом, игра с другом по ссылке.

non-functional:
  - Оптимизация скорости работы и удобства использования сайта.
  - Обеспечение безопасности и защиты данных пользователей.
  - Поддержка удобства использования на мобильных устройствах.
  - Тестирование на совместимость с последними версиями браузеров.
  - Способность обрабатывать большое количество трафика, например, 1000 одновременных пользователей.

implicit:
  - Непрерывное развитие и обновление функциональности на основе обратной связи от пользователей и сообщества.
  - Поддержка и поощрение активного участия сообщества в развитии проекта.
